Repository fga-gpp-mds/2018.1-Dr-Down, pull requests merged in 2018-06, with the labels that each got.

#264 Processo do Pipeline
  docs/eps/PIPELINE.md
Labels: deploy, devops, documentation, eps, refactoring

#281 TS115 - Environment Reviews
  config/settings/local.py
  config/settings/production.py
Labels: Important, deploy, devops, hard, help wanted, production, staging

#280 Feature/us113 api connection
  drdown/medicalrecords/admin.py
  drdown/medicalrecords/forms/curves_form.py
  drdown/medicalrecords/locale/pt_BR/LC_MESSAGES/django.po
  drdown/medicalrecords/migrations/0011_auto_20180606_1307.py
  drdown/medicalrecords/models/model_curves.py
  drdown/medicalrecords/static/medicalrecords/css/medicalrecords.css
  drdown/medicalrecords/static/medicalrecords/js/curves.js
  drdown/medicalrecords/templates/medicalrecords/curves.html
  drdown/medicalrecords/templates/medicalrecords/medicalrecord_curves_form.html
  drdown/medicalrecords/templates/medicalrecords/medicalrecord_list.html
  drdown/medicalrecords/tests/test_model_curves.py
  drdown/medicalrecords/tests/test_view_curves.py
  drdown/medicalrecords/urls.py
  drdown/medicalrecords/views/view_curves.py
  drdown/medicalrecords/views/view_medical_record.py
  drdown/medicalrecords/views/view_pdf.py
  drdown/medicalrecords/views/views_base.py
  drdown/users/templates/users/user_detail.html
  utility/populate.py
Labels: backend, code, enhancement, feature, frontend, mds, micro serviço

#297 Update PIPELINE.md
  docs/eps/PIPELINE.md
Labels: Important, devops, documentation, enhancement, eps

#302 Feature/us121 email notifications
  .gitignore
  config/settings/base.py
  config/settings/test.py
  drdown/appointments/models/model_request.py
  drdown/appointments/tests/test_view_request.py
  drdown/careline/templates/careline/checklist_detail.html
  drdown/events/models/model_events.py
  drdown/events/tests/test_model_events.py
  drdown/notifications/locale/pt_BR/LC_MESSAGES/django.po
  drdown/notifications/templates/notifications/emails/appointment_canceled.html
  drdown/notifications/templates/notifications/emails/appointment_sucess.html
  drdown/notifications/templates/notifications/emails/careline_check.html
  drdown/notifications/templates/notifications/emails/create_event.html
  drdown/notifications/templates/notifications/emails/update_event.html
  drdown/notifications/templates/notifications/patient_notifications.html
  drdown/notifications/templates/notifications/responsible_notifications.html
  drdown/notifications/utils/__init__.py
  drdown/notifications/utils/mail.py
  drdown/users/models/model_patient.py
  drdown/users/tests/test_model_patient.py
Labels: backend, enhancement, feature, mds

#328 Finalizando documento de arquitetura
  docs/mds/ARCHITECTURE_DOCUMENT.md
Labels: architecture

#333 Corrigindo erro na model employee
  drdown/users/migrations/0020_auto_20180621_1831.py
  drdown/users/models/model_employee.py
Labels: bug

#337 Correcting card spacing in notifications
  drdown/notifications/templates/notifications/employee_notifications.html
  drdown/notifications/templates/notifications/health_team_notifications.html
  drdown/notifications/templates/notifications/patient_notifications.html
  drdown/notifications/templates/notifications/responsible_notifications.html
Labels: hotfix

#336 Refatoração de código
  drdown/appointments/views/view_appointment.py
  drdown/appointments/views/view_request.py
  drdown/careline/views/view_checklist.py
  drdown/users/adapters.py
  drdown/users/models/model_employee.py
  drdown/users/models/model_health_team.py
  drdown/users/models/model_patient.py
  drdown/users/models/model_responsible.py
  drdown/users/models/model_user.py
  drdown/users/tests/test_model_employee.py
Labels: backend, code, refactoring, refatoração

#342 Fixing pipeline image link
  docs/eps/PIPELINE.md
Labels: bug, documentation, easy, hotfix
