Repository fga-gpp-mds/2018.1-Dr-Down, pull requests merged in 2018-05, with the labels that each got.

#210 Pipeline Doc
  docs/eps/PIPELINE.md
  mkdocs.yml
Labels: Important, PO, deploy, devops, documentation, eps, mds, medium, scrum master

#226 Support/ts91 refactor vaccination
  drdown/core/locale/pt_BR/LC_MESSAGES/django.po
  drdown/core/static/core/css/vaccineshedule.css
  drdown/core/static/core/images/Subtitle.png
  drdown/core/templates/core/vaccine_schedule.html
Labels: PO, frontend, refactoring, refatoração

#232 CI/CD Revision
  .travis.yml
  mkdocs-build.sh
Labels: deploy, devops, documentation, eps

#259 Removing Sentry Configuration
  config/settings/base.py
Labels: Important, devops, easy, eps, hotfix, mds, production, staging
