Repository fga-gpp-mds/2018.1-Dr-Down, pull requests merged in 2018-04, with the labels that each got.

#77 TS44 mkdocs
  docs/eps/EAP.md
  docs/eps/ROADMAP.md
  docs/index.md
  docs/mds/ADDITIONAL_SPECIFICATION.md
  docs/mds/ARCHITECTURE_DOCUMENT.md
  mkdocs.yml
Labels: documentation, eps

#108 TS49 Refactor High Fidelity Prototype
  docs/mds/HIGH_FIDELITY_PROTOTYPE.md
  docs/mds/HIGH_FIDELITY_PROTOTYPE.xd
Labels: PO, documentation, frontend, mds, medium, refactoring, refatoração

#109 HOTFIX - Adding the new docks on mkdocs
  docs/mds/LOW_FIDELITY_PROTOTYPE.md
  mkdocs.yml
Labels: documentation, easy, hotfix

#117 TS52 Refactor Homepage
  drdown/static/css/home.css
  drdown/static/css/info.css
  drdown/static/css/project.css
  drdown/static/css/user_detail.css
  drdown/static/homepage/css/freelancer.css
  drdown/static/homepage/vendor/font-awesome/css/font-awesome.min.css
  drdown/static/homepage/vendor/font-awesome/fonts/FontAwesome.otf
  drdown/static/homepage/vendor/font-awesome/fonts/fontawesome-webfont.eot
  drdown/static/homepage/vendor/font-awesome/fonts/fontawesome-webfont.svg
  drdown/static/homepage/vendor/font-awesome/fonts/fontawesome-webfont.ttf
  drdown/static/homepage/vendor/font-awesome/fonts/fontawesome-webfont.woff
  drdown/static/homepage/vendor/font-awesome/fonts/fontawesome-webfont.woff2
  drdown/templates/account/login.html
  drdown/templates/account/signup.html
  drdown/templates/base.html
  drdown/templates/pages/home.html
  drdown/templates/pages/info.html
  drdown/templates/users/user_detail.html
  drdown/templates/users/user_form.html
  drdown/users/migrations/0007_auto_20180410_2308.py
  drdown/users/models/model_user.py
Labels: code, frontend, mds, medium, refactoring, refatoração

#121 Fixing star color in Down's Syndrome Page
  drdown/templates/pages/info.html
Labels: bug, easy, frontend

#125 Modifying the project architecture
  docs/mds/ARCHITECTURE_DOCUMENT.md
Labels: architecture

#157 TS61 Refactor Employee User
  drdown/templates/admin/change_form.html
  drdown/templates/users/user_detail.html
  drdown/users/admin.py
  drdown/users/migrations/0009_auto_20180418_1936.py
  drdown/users/models/model_employee.py
  drdown/users/tests/test_model_employee.py
  drdown/users/tests/test_model_user.py
  drdown/users/tests/test_view_employee.py
Labels: backend, code, mds, refactoring

#159 Bugfix/release 01
  docs/eps/CANVAS.md
  docs/eps/EAP.md
  docs/eps/ROADMAP.md
  docs/eps/SCRUM_METHODOLOGY_DRDOWN.md
  docs/mds/ARCHITECTURE_DOCUMENT.md
  docs/mds/VISION_DOCUMENT.md
  docs/sprints/00/planning.md
  docs/sprints/01/planning.md
  docs/sprints/02/planning.md
  docs/sprints/03/planning.md
  docs/sprints/04/planning.md
  docs/sprints/05/planning.md
Labels: bug

#169 TS72 Refatorar Time de Saúde
  drdown/core/locale/pt_BR/LC_MESSAGES/django.po
  drdown/forum/locale/pt_BR/LC_MESSAGES/django.po
  drdown/users/locale/pt_BR/LC_MESSAGES/django.po
  drdown/users/migrations/0013_auto_20180424_1733.py
  drdown/users/models/model_health_team.py
  drdown/users/models/model_patient.py
  drdown/users/models/model_responsible.py
  drdown/users/models/model_user.py
  drdown/users/templates/users/user_detail.html
  drdown/users/tests/test_model_health_team.py
  drdown/users/tests/test_model_user.py
  drdown/users/tests/test_view_health_team.py
Labels: code, mds, medium, refactoring

#176 BUGFIX - Correções gerais
  drdown/core/templates/core/base.html
  drdown/users/locale/pt_BR/LC_MESSAGES/django.po
  drdown/users/migrations/0014_auto_20180424_2032.py
  drdown/users/models/model_health_team.py
  drdown/users/models/model_user.py
  drdown/users/templates/users/user_detail.html
  drdown/users/utils/validators.py
Labels: URGENTE, backend, bug, hard, mds

#178 Review CI
  .gitignore
  .travis.yml
  docs/conf.py
  docs/drdown.pdf
  docs/index.rst
  mkdocs-build.sh
Labels: Important, devops, documentation, eps, mds, medium

#181 #HOTFIX: Reorganizing .travis.yml
  .travis.yml
Labels: bug, devops, hotfix

#190 EVM - Segunda Release
  .travis.yml
  docs/eps/EVM_AGILE.md
  drdown/users/tests/test_model_user.py
  mkdocs-build.sh
Labels: Important, PO, URGENTE, documentation, eps, help wanted, medium, metrics, métrica, scrum master

#193 HOTFIX: Corrigindo um erro em teste que apenas ocorre em datas específicas
  drdown/users/models/model_user.py
  drdown/users/tests/test_model_user.py
  requirements/base.txt
Labels: URGENTE, backend, bug
