Repository fga-gpp-mds/2018.1-Dr-Down, pull requests merged in 2018-03, with the labels that each got.

#31 Criando o bootstrap do projeto e configurando docker de desenvolvimento
  .gitignore
  Dockerfile
  Makefile
  README.md
  dev.sh
  docker-compose-dev.yml
  drdown/__init__.py
  drdown/config/apps.py
  drdown/config/database.py
  drdown/config/files.py
  drdown/config/i18n.py
  drdown/config/messages.py
  drdown/config/middleware.py
  drdown/config/password.py
  drdown/config/security.py
  drdown/config/templates.py
  drdown/settings.py
  drdown/urls.py
  drdown/wsgi.py
  manage.py
  requirements.txt
Labels: devops, eps

#16 Submetendo documento de visão
  docs/VISION_DOCUMENT.md
Labels: documentation, mds

#53 Update .travis.yml
  .travis.yml
Labels: bug, devops, easy, eps, metrics, métrica, refactoring

#51 Configuração inicial do code climate
  codeclimate.yml
Labels: devops, easy, eps, métrica

#48 Support/scrum documentation
  docs/documentacao_Scrum_Dr_Down.md
Labels: documentation, eps, scrum master

#52 Adição de recurso do produto ao Documento de Visão
  docs/VISION_DOCUMENT.md
Labels: PO, documentation, easy, mds, refactoring, scrum master

#59 Adding the EAP
  docs/EAP.md
Labels: PO, documentation, eps, refactoring, scrum master

#49 TS29 - Refatorar a documentação da sprint 00 e 01
  docs/sprints/00/planning.md
  docs/sprints/00/results.md
  docs/sprints/01/planning.md
  docs/sprints/01/results.md
Labels: documentation, eps, refactoring, scrum master

#55 Documentação da sprint 02
  .github/CONTRIBUTING.md
  docs/EAP.md
  docs/sprints/02/planning.md
  docs/sprints/02/results.md
Labels: PO, documentation, eps, scrum master

#45 Inserindo o mkdocs como servidor para o site de documentação
  Makefile
  README.rst
  docs/TAP.md
  docs/VISION_DOCUMENT.md
  docs/index.md
  mkdocs.yml
  requirements/base.txt
Labels: documentation, medium

#57 ROADMAP
  docs/ROADMAP.md
Labels: PO, documentation, eps, scrum master

#62 Making architecture document
  docs/ARCHITECTURE_DOCUMENT.md
Labels: architecture, documentation, mds
